### The purpose of this file is to add 20 abstracts each from INFORMS and IISE to the gemini-generated pre-existing test prompts list, which will be used to evaluate the model's retrieval and reranking.

#### This script takes 20 abstracts at random from the IISE and INFORMS datasets and appends them to the testing_queries file.

In [1]:
import pandas as pd

In [ ]:
iise_dataset_filepath = './Datasets/IISE 2024/IISE2024_Processed.csv'
informs_dataset_filepath = r'.\Datasets\INFORMS 2024\INFORMS2024_processed.csv'
iise_queries_filepath = './Datasets/IISE 2024/Queries/testing_queries.xlsx'
informs_queries_filepath = r'./Datasets/INFORMS 2024/Queries/testing_queries.xlsx'

iise_df = pd.read_csv(iise_dataset_filepath)
informs_df = pd.read_csv(informs_dataset_filepath)

iise_queries = pd.read_excel(iise_queries_filepath, header=None)
informs_queries = pd.read_excel(informs_queries_filepath, header=None)
iise_queries.rename(columns={iise_queries.columns[0]: "Prompt"}, inplace=True)
informs_queries.rename(columns={informs_queries.columns[0]: "Prompt"}, inplace=True)

display(iise_queries.head(5))
display(informs_queries.head(5))

display(iise_df.head(5))
display(informs_df.head(5))

                                     Prompt
0        supply chain resilience strategies
1    discrete event simulation applications
2               ergonomics in manufacturing
3            lean healthcare implementation
4  data analytics for operations management

                         Prompt
0       Stochastic optimization
1       Supply chain resilience
2   Revenue management airlines
3         Healthcare scheduling
4  Machine learning forecasting

,paper_title,abstract,session_name,session_id,paper_id
0,Optimizing Operations Managerial Performance: ...,Senior company leadership at an aircraft main...,Optimization,154,1
1,Discovering Puerto Rico Roads Profile Influenc...,The infrastructure of Puerto Rico (PR) was gi...,Logistics I,122,2
2,Designing Manufacturing Enterprises System for...,"Currently, researchers are concentrating thei...",Process Planning-I,180,3
3,Achieving Equitable Access to Medical Laborato...,"In contemporary healthcare, laboratory tests ...",Social Good Analytics,209,4
4,A Simulation-Based Case Study on ICU Patients ...,Intensive care units (ICUs) provide critical ...,Healthcare Optimization,87,5

,paper_id,session_name,paper_title,abstract,session_id
0,0,D-Wave Quantum Optimization,Quantum Optimization,Quantum computing has gone from the lab to the...,1
1,1,GAMSPy and Data APIs for Streamlining Optimiza...,GAMSPy and Data APIs for Streamlining Optimiza...,GAMS (General Algebraic Modeling System) is an...,2
2,2,Elevate your Optimization Practice with latest...,Elevate your Optimization Practice with latest...,Join our workshop to discover the cutting-edge...,3
3,3,Analyzing Multidimensional Data and building P...,Analyzing Multidimensional Data and building P...,Fully analyzing data requires an analyst to ge...,4
4,4,"Hexaly, a New Kind of Global Optimization Solver","HEXALY, A New Kind of Global Optimization Solver",Hexaly is a new kind of global optimization so...,5

In [11]:
def sample_and_append_rows(
    source_df: pd.DataFrame,
    source_column_name: str,
    n: int,
    target_df: pd.DataFrame,
    target_column_name: str,
    replace: bool = False
) -> pd.DataFrame:
    """
    Samples n random values from a source DataFrame column and appends them
    as new rows to a target DataFrame under a specified column name.

    Args:
        source_df: The pandas DataFrame to sample from.
        source_column_name: The name of the column in source_df to sample values from.
        n: The number of random values to sample.
        target_df: The pandas DataFrame to append the sampled values to.
        target_column_name: The name of the column in target_df where the
                             sampled values will be added. If this column doesn't
                             exist in target_df, it will be created, with NaN
                             values for the original rows.
        replace: Whether to sample with replacement (allow picking the same
                 source value multiple times). Defaults to False.

    Returns:
        A new pandas DataFrame containing the original target_df rows plus
        n new rows with the sampled values under target_column_name.

    Raises:
        ValueError: If n is negative or larger than the source column size
                    when replace=False.
        KeyError: If source_column_name does not exist in source_df.
        TypeError: If source_df or target_df are not pandas DataFrames.
    """
    # --- Input Validation ---
    if not isinstance(source_df, pd.DataFrame):
        raise TypeError("source_df must be a pandas DataFrame")
    if not isinstance(target_df, pd.DataFrame):
        raise TypeError("target_df must be a pandas DataFrame")
    if not isinstance(source_column_name, str):
        raise TypeError("source_column_name must be a string")
    if not isinstance(target_column_name, str):
        raise TypeError("target_column_name must be a string")
    if not isinstance(n, int) or n < 0:
        raise ValueError("n must be a non-negative integer")
    if source_column_name not in source_df.columns:
        raise KeyError(f"Column '{source_column_name}' not found in source_df")

    if n == 0:
        print("Warning: n is 0, no samples taken. Returning original target_df.")
        # Return a copy to maintain consistency of returning a new DataFrame
        return target_df.copy()

    # Check if sampling is possible (n vs source size) only if replace=False
    if not replace and n > len(source_df):
         raise ValueError(f"Cannot sample n={n} items without replacement "
                          f"from a column of size {len(source_df)}")

    # --- Core Logic ---
    try:
        # 1. Sample n values from the specified source column
        sampled_values = source_df[source_column_name].sample(n=n, replace=replace)

        # 2. Create a temporary DataFrame from the sampled values
        #    The column name in this temp DataFrame should be the target column name
        temp_df = pd.DataFrame({target_column_name: sampled_values})

        # 3. Append the temporary DataFrame rows to the target DataFrame
        #    ignore_index=True creates a new clean index for the combined DataFrame
        result_df = pd.concat([target_df, temp_df], ignore_index=True, sort=False)

        return result_df

    except ValueError as e:
         # Catch potential errors from .sample() if checks missed something
         print(f"Error during sampling: {e}")
         raise # Re-raise the error after printing
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        raise # Re-raise

iise_ap_queries = sample_and_append_rows(iise_df, 
                                      'abstract', 
                                      target_df=iise_queries, 
                                      target_column_name='Prompt',
                                      n=20,
                                      replace=False)

informs_ap_queries = sample_and_append_rows(informs_df, 
                                      'abstract', 
                                      target_df=informs_queries, 
                                      target_column_name='Prompt',
                                      n=20,
                                      replace=False)

display(iise_ap_queries.tail(25))
display(informs_ap_queries.tail(25))

                                               Prompt
45  How does one apply human factors engineering p...
46  What are the current challenges and future opp...
47  How can operations research techniques be appl...
48  What innovative strategies significantly enhan...
49  How to accurately measure and systematically i...
50   Healthcare informatics as a field advanced as...
51   It is common in quality control problems that...
52   Alginate's viscosity enhancement capacity by ...
53   Culture has a tremendous influence on identit...
54   Industrial robots are a crucial technology fo...
55   This investigative study examines the impact ...
56   In response to challenges in high-mix low-vol...
57   In developing countries, the geographical acc...
58   In various industrial applications, particula...
59   There is a huge lack of qualified personnel i...
60   Utilizing Boston Dynamics' robotic dog, Spot,...
61   Assessments play a critical role in all autom...
62   Nurses’ attrition is a pressing global concer...
63   This groundbreaking research introduces an in...
64   Particulate matter and gaseous emissions in D...
65   Day-ahead markets for electrical power allow ...
66   Although preventable, dental caries (cavities...
67   Manufactured components oftentimes necessitat...
68   In response to the pressing nursing shortage,...
69   I’ve experienced traditional Root Cause Analy...

                                               Prompt
45  How to incorporate fairness and ethical consid...
46  Analyzing the impact of behavioral biases on o...
47  Natural language processing techniques for ext...
48  Advanced analytics for optimizing omnichannel ...
49  What are the computational challenges and rece...
50  Video has emerged as a pervasive medium for co...
51  AI recommendation systems have become ubiquito...
52  An energy company attempts to leverage the inf...
53  Strategic product placement can have a strong ...
54  The COVID-19 pandemic and work-from-home polic...
55  We discuss a project that combines three large...
56  The U.S. inland waterway transportation system...
57  Column elimination is an exact method for solv...
58  In multistage manufacturing processes, quality...
59  This study develops a mixed integer non-linear...
60  The analysis of big patient data provides enor...
61  Data splitting is an important step in predict...
62  When multiple stakeholders are affected by the...
63  The weighted-workload-task-allocation (WWTA) l...
64  Perovskite solar cells hold significant potent...
65  In this paper, we study the optimization of th...
66  With the rise of e-commerce, delivery vehicles...
67  Monitoring returns through stock price predict...
68  Choice-based conjoint (CBC) experiments are wi...
69  The recent advent of data-driven and end-to-en...

In [12]:
iise_ap_queries.to_excel(r'C:\Users\Tillman\Thesis\Datasets\IISE 2024\Queries\testing_queries.xlsx')
informs_ap_queries.to_excel(r'C:\Users\Tillman\Thesis\Datasets\INFORMS 2024\Queries\testing_queries.xlsx')